spring:
  #配置数据库源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  #扫描mapper映射文件所在的目录,扫描resources/mapper目录下所有的以.xml为后缀的文件
  mapper-locations: classpath:mapper/*.xml
  #实体类取别名
  type-aliases-package: com.lindong.myoasystem.pojo
  configuration:
    #启用日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl