server:
  port: 8888
  servlet:
    context-path: /manage
spring:
  profiles:
    active: mapper

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd